### ISSUE TITLE
Click again to close focused image not working

### ISSUE THREAD

**Issue by epicstar7** [JonahGrimm/Meisunry#5]
Click again to close focused image doesn't seem to work anymore, after trying several times

**Comment by JonahGrimm** [comment]
I removed the feature and replaced it with a close button in the bottom left corner. This is because there is now a pan option when you click and drag.

That being said... I myself am missing the click to close lol. It's very easy to re-add, but I can't think of the right way to re-implement it so that it does not conflict with the drag to pan the image.

**Comment by epicstar7** [comment]
Maybe use middle mouse for closing or panning instead of using both middle and left mouse for panning. Or just use your mouse movement to screen edge for panning. Or change something around with the right click menu, and make buttons for specific actions you really need from that menu, like deleting an image. Then use right click for closing or panning.

**Comment by JonahGrimm** [comment]
https://github.com/JonahGrimm/Meisunry/releases/tag/v9
